language: node_js
node_js: stable

branches:
  only:
  - blog

before_install:
- npm install -g hexo-cli

cache:
  directories:
    - node_modules

install:
- npm install
- npm install hexo-deployer-git --save
- npm install hexo-generator-searchdb --save

script:
- hexo clean
- hexo generate

after_success:
- git config --global user.name "fdawork"
- git config --global user.email "60561872+fdawork@users.noreply.github.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo deploy --silent
